### ISSUE TITLE
[Web5 Upgrade]: 0.8.3

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#1033]
### Tasks

- [x] (Web5 Team) Cut preview/alpha release for acceptance testing. Version: [`@web5/user-agent@0.8.3-rc.0`](https://www.npmjs.com/package/@web5/api/v/0.8.3-rc.0).
- [x] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza).
  - [x] Link to branch with passing bundler-bonanza w/ upgraded Web5 dep: [bundler-bonanza/pull/74](https://github.com/TBD54566975/bundler-bonanza/pull/74)
      _**Note:** Still working to resolve remaining React Native Issue._
- [x] (Open Source Programs Engineering) Create new branch on site repo for the upgrade
  - [x] Branch: [release-0.8.3](https://github.com/TBD54566975/developer.tbd.website/tree/release-0.8.3)
- [ ] Manually Check examples that do not yet have automated tests:
  - [x] `book-review`
  - [ ] `resolve` method > could be turned into code snippet 
- [x] (Open Source Programs Engineering) Open PR on this branch
  - [ ] PR: [release PR](https://github.com/TBD54566975/developer.tbd.website/pull/1054)
- [x] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. to activate Deploy Previews in Netlify
  - [x] [Deploy Preview](https://deploy-preview-1054--tbd-website-developer.netlify.app/) 
- [x] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [x] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [x] (Open Source Programs Engineering) Check results of tests
  - [x] [Tests](https://github.com/TBD54566975/developer.tbd.website/actions/runs/7116826622)
- [x] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
  - [x] `site/__tests__/quickstart.test.js`
    - [x] `recordResult successfully deletes the record` - TypeError: record.delete is not a function
  - [x] `examples/web5-quickstart-widgets/__tests__/widget.test.js`
    - [x] `recordResult successfully deletes the record` - TypeError: recordResult.delete is not a function
  - [x] `site/__tests__/api/web5-js/dwn/protocol.test.js`
    - [x] `configureProtocolAndSend sends a protocol to remote DWNs` - AssertionError: expected 400 to be 202 // Object.is equality
  - [x] `site/__tests__/api/web5-js/dwn/record.test.js`
    - [x] `deleteRecord deletes the updated record` - TypeError: record.delete is not a function
  - [x] `site/__tests__/api/web5-js/dwn/records.test.js`
    - [x] `queryPlaylistFromDid queries records` - TypeError: Cannot read properties of undefined (reading 'map')
    - [x] `readRecordByIdFromDid reads a record by ID from a specific DID` - TypeError: Cannot read properties of undefined (reading 'data')
    - [x] `deleteRecordFromDid deletes a record` - AssertionError: expected 400 to be 202 // Object.is equality
  - [x] `site/__tests__/web5/build/decentralized-web-nodes/delete-from-dwn.test.js`
    - [x] `deleteFromLocalDWN deletes a record` - TypeError: record.delete is not a function
  - [x] `site/__tests__/web5/build/decentralized-web-nodes/query-from-dwn.test.js`
    - [x] `queryRecordsFromDid returns an array of records` - TypeError: Cannot read properties of undefined (reading 'map')
  - [x] `site/__tests__/web5/build/decentralized-web-nodes/send.test.js`
    - [x] `sendRecordToRemoteDWNs sends record` - AssertionError: expected 400 to be 202 // Object.is equality
    - [x] `sendProtocolToRemoteDWNs sends a protocol` - AssertionError: expected 400 to be 202 // Object.is equality
    - [x] `sendRecordToDWNOfRecipient can be configured` - AssertionError: expected 400 to be 202 // Object.is equality
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch

Still on the works...
- [ ] (Open Source Programs Engineering) Retrain AskGPT bot on new data

Dismissed, since we are not publishing API Reference for Web5JS yet...
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~
- [ ] ~~(Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream~~
