### ISSUE TITLE
[Web5 Upgrade]: Dinger tutotial update

### ISSUE THREAD

**Issue by Vikrant-Khedkar** [TBD54566975/developer.tbd.website#1065]
### Tasks

- [X] (Web5 Team) Cut preview/alpha release for acceptance testing. Version - versionNumberHere. Link - here.
- [X] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to branch with passing bundler-bonanza w/ upgraded Web5 dep -
- [X] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. Branch - Link here
- [X] (Open Source Programs Engineering) Open PR on this branch. PR - Link here
- [X] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. Deploy Preview - Link here
- [X] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [X] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [X] (Open Source Programs Engineering) Check results of tests
- [X] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [X] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [X] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [X] (Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.
- [X] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream
- [X] (Open Source Programs Engineering) Retrain AskGPT bot on new data

**Comment by Vikrant-Khedkar** [comment]
In the dinger tutorial on web5 docs we have mentioned "Find this console logs in the index.js and update them with the given code one by one" But when we pull the gitHub repo the code is already complete.
![image](https://github.com/TBD54566975/developer.tbd.website/assets/64966091/6819d4e8-bdc5-4879-8a90-45e326c57b41)
![image](https://github.com/TBD54566975/developer.tbd.website/assets/64966091/bc32ae0f-9898-42c9-918a-6b17746b7c91)

**Comment by blackgirlbytes** [comment]
there's two different versions of the app. one that's complete and one that's not complete. you have to look for the dinger-starter (that's incomplete). Dinger-completed is already complete

**Comment by Vikrant-Khedkar** [comment]
okay my bad
