### ISSUE TITLE
[Web5 JS Update]: `@web5/api@0.8.4`

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/developer.tbd.website#1129]
### Tasks

- [x] (Web5 Team) Cut release candidate for acceptance testing. Version `0.8.4-rc.0` [on NPM Registry](https://www.npmjs.com/package/@web5/api/v/0.8.4-rc.0).
- [x] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to [branch with passing bundler-bonanza w/ upgraded Web5 dep](https://github.com/TBD54566975/bundler-bonanza/pull/77)
- [x] (Open Source Programs Engineering) Open PR on this branch. PR - [Pull Request](https://github.com/TBD54566975/developer.tbd.website/pull/1146)
- [x] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. [Deploy Preview](https://deploy-preview-1146--tbd-website-developer.netlify.app/)
- [x] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [x] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [x] (Open Source Programs Engineering) Manually check QuickStart (required as manual until Issue 1093 is completed)
- [x] (Open Source Programs Engineering) Check results of tests
- [x] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass - [Test results](https://github.com/TBD54566975/developer.tbd.website/actions/runs/7494386495/job/20402197488)
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [x] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream

Out of scope because not needed (no API changes):
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~
- [ ] ~~(Open Source Programs Engineering) Retrain AskGPT bot on new data~~

**Comment by ALRubinger** [comment]
Thank you @frankhinek!

**Comment by leordev** [comment]
PR #1146 merged, the release is complete
