### ISSUE TITLE
[Web5 Upgrade]: @web5/api@0.9.1

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/developer.tbd.website#1310]
### Tasks

- [x] (Web5 Team) Describe expected impact of this release. API Changes? (👍/👎) DWN Wire Incompatibility requiring hosted DWN server reset? (👍/👎)
- [x] (Web5 Team) Cut preview/alpha release for acceptance testing. Version - 0.4.3-alpha-20240402-18e0b07. Link - [here](https://www.npmjs.com/package/@web5/api/v/0.9.0-alpha-20240402-18e0b07).
- [x] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to branch with passing bundler-bonanza w/ upgraded Web5 dep -
- [x] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. 
    - Branch **leordev/api-0.9.1-release**
- [x] (Open Source Programs Engineering) Open PR on this branch. 
    - PR: https://github.com/TBD54566975/developer.tbd.website/pull/1375
- [x] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. 
    - Deploy Preview: https://deploy-preview-1375--tbd-website-developer.netlify.app/
- [x] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [x] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [x] (Open Source Programs Engineering) Manually check QuickStart (required as manual until Issue 1093 is completed)
- [x] (Open Source Programs Engineering) Check results of tests
- [x] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
    - Latest PR commit is green ✅: https://github.com/TBD54566975/developer.tbd.website/pull/1375/commits/00c81a828a5a3455da6abc332b808ced1757de6b
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [x] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream

Skipped:
- [ ] ~~(Open Source Programs Engineering) Retrain AskGPT bot on new data~~

Deprecated:
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~ -- every new release publishes the API Docs in the external API Reference links automatically.
