### ISSUE TITLE
[tbDEX Upgrade]: Release Checklist Pilot

### ISSUE THREAD

**Issue by leordev** [TBD54566975/developer.tbd.website#1362]
**Packages in the Release**

| Package                 | Preview/Snapshot | Next Release Version |
| ----------------------- | ---------------- | -------------------- |
| @web5/common (js)       | snapshot_sha     | vN.N.N               |
| @web5/credentials (js)  | snapshot_sha     | vN.N.N               |
| @web5/crypto (js)       | snapshot_sha     | vN.N.N               |
| @web5/dids (js)         | snapshot_sha     | vN.N.N               |
| @tbdex/http-client (js) | snapshot_sha     | vN.N.N               |
| @tbdex/http-server (js) | snapshot_sha     | vN.N.N               |
| @tbdex/protocol (js)    | snapshot_sha     | vN.N.N               |
| web5-kt                 | snapshot_sha     | vN.N.N               |
| tbdex-kt                | snapshot_sha     | vN.N.N               |
| web5-swift              | snapshot_sha     | vN.N.N               |
| tbdex-swift             | snapshot_sha     | vN.N.N               |

- [ ] _Fill the packages information that you want to release above, remove the ones that you don't need to include in this release._

**Pre-Release Stage**

- [ ] (tbDEX SDK Team) Describe expected impact of this release.
  - API Breaking Changes? (👍/👎)
      - Breaking changes after v1 MUST bump major
      - If not ready for major bump, consider adding new interfaces
- [ ] (tbDEX SDK Team) Make sure license and security checks are green.
- [ ] (tbDEX SDK Team) Cut the preview snapshot for acceptance testing.
  - Swift: automated, just indicate the commit sha
  - JS: automated, just indicate the commit sha
  - Kotlin:
    - (pre-maven) cut the SNAPSHOT version following the steps on readme and indicate the version here
    - (post-maven) automated, just indicate the commit sha
  - _Snapshot Version should be indicated in the GH Issue Thread below as a comment_
- [ ] Start a Discord Thread about this Release
  - Discord Thread Link: https://discord.com/channels/XXXXXXX/XXXXXXX
- [ ] (OSP Team) Open PR on dev-website pointing to the preview snapshot
  - PR: https://github.com/TBD54566975/developer.tbd.website/pull/NNNN
- [ ] (OSP Team) This will trigger a Deploy Preview on Netlify.
  - Deploy Preview: https://deploy-preview-NNNN--tbd-website-developer.netlify.app/
- [ ] (OSP Team) Run the monorepo tests - this will cover code snippets and examples
  - Tests Results link (MUST be ✅): https://github.com/TBD54566975/developer.tbd.website/actions/runs/NNNNNNN
- [ ] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
  - **Note to teams**: there may be a back and forth if DevRel discovers upstream issues that need to be addressed, with new Snapshots if so

**Final Release Stage**

- [ ] (tbDEX SDK Team) Cut the final release of the package next version
- [ ] (OSP Team) Update package final release version in the dev-website PR
- [ ] (OSP Team) Rebase, check tests and merge PR to `main`
