### ISSUE TITLE
[Web5 Upgrade]: `@web5/api` `v0.9.3` & `@web5/agent(-*)` `v0.3.2`

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/developer.tbd.website#1402]
A new release for `api` as well as deploying a new `dwn-server`.

The server has some new features, but also this push will remedy a few CVEs that have popped up, so we will see everything go to green after this. (until the next one!)

Additionally the other critical change is that a bad `did` resolution is no longer cached. This was causing some issues where in some cases a `web5` user would not be able to access their app because of a bad `did` resolution and the app would just fail for the 15 minute cache.

The only breaking change for the `api` with this push is a renaming from `permissionsGrantId` field to `permissionGrantId`.

Additionally the DB will be cleared due to some changes in indexing parameters.

As far as new features, we have also added `tags` to `Records`. This is an additive feature and does not break any existing APIs but rather adds a field to be used in `create` and `query`.

### Tasks

- [X] (Web5 Team) Flag expected impact of this release. 
    - API Changes? 👍 
    - DWN Wire Incompatibility requiring hosted DWN server reset?👍
- [X] (Web5 Team) Cut preview/alpha release for acceptance testing. Version 0.9.3 
- [X] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). 
    - Link to branch with passing bundler-bonanza w/ upgraded Web5 dep: https://github.com/TBD54566975/bundler-bonanza/pull/82#pullrequestreview-2029605922
- [X] (Open Source Programs Engineering) Create new branch on devsite repo for the upgrade, bump relevant packages to the next version and open a PR.
    - PR: https://github.com/TBD54566975/developer.tbd.website/pull/1405
- [X] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. 
    - Deploy Preview: https://deploy-preview-1405--tbd-website-developer.netlify.app/
- [X] (Open Source Programs Engineering) Check PR tests are green - this will cover code snippets and examples
- [X] (Open Source Programs Engineering) Manually check QuickStart (required as manual until #1093 is completed)
- [x] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [x] (Open Source Programs Engineering) Rebase and merge devsite PR to `main`, make sure tests are still green, and merge; Release is complete!

Deprecated:
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~ 
- [ ] ~~(Open Source Programs Engineering) Retrain AskGPT bot on new data~~

**Comment by finn-tbd** [comment]
closing per request from @leordev
