### ISSUE TITLE
[Web5 Upgrade]: `@web5/api` `v0.9.4`

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/developer.tbd.website#1437]
### Tasks

- [X] (Web5 Team) Describe expected impact of this release. API Changes? (👍/👎) DWN Wire Incompatibility requiring hosted DWN server reset? (👍/👎)
   - Optional boolean property `prune` added to `records.delete()` api. This deletes a parent record and prunes any of the children.
   - DWN Server is being upgraded, some data may be lost.
- [X] (Web5 Team) Cut preview/alpha release for acceptance testing. Version - 0.4.9. Link - [0.4.9-alpha-20240528-cc47014](https://www.npmjs.com/package/@web5/api/v/0.9.4-alpha-20240528-cc47014).
- [X] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to branch with passing bundler-bonanza w/ upgraded Web5 dep - https://github.com/TBD54566975/bundler-bonanza/pull/84
- [X] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. Branch - [Link here](https://github.com/TBD54566975/developer.tbd.website/tree/leordev/web5-api-0.9.4-release)
- [X] (Open Source Programs Engineering) Open PR on this branch. PR - [Link here](https://github.com/TBD54566975/developer.tbd.website/pull/1438)
- [X] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. Deploy Preview - [Link here](https://deploy-preview-1438--tbd-website-developer.netlify.app/)
- [X] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [X] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [X] (Open Source Programs Engineering) Manually check QuickStart (required as manual until Issue 1093 is completed)
- [X] (Open Source Programs Engineering) Check results of tests
- [X] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [x] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream

Deprecated:
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~
- [ ] ~~(Open Source Programs Engineering) Retrain AskGPT bot on new data~~
