### ISSUE TITLE
[Web5 Upgrade]: v0.10.0

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#1472]
### Tasks

- [ ] (Web5 Team) Describe expected impact of this release. API Changes? (👍/👎) DWN Wire Incompatibility requiring hosted DWN server reset? (👍/👎)
- [ ] (Web5 Team) Cut preview/alpha release for acceptance testing. Version - versionNumberHere. Link - here.
- [ ] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to branch with passing bundler-bonanza w/ upgraded Web5 dep -
- [ ] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. Branch - Link here
- [ ] (Open Source Programs Engineering) Open PR on this branch. PR - Link here
- [ ] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. Deploy Preview - Link here
- [ ] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [ ] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [ ] (Open Source Programs Engineering) Manually check QuickStart (required as manual until Issue 1093 is completed)
- [ ] (Open Source Programs Engineering) Check results of tests
- [ ] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [ ] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [ ] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [ ] (Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.
- [ ] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream
- [ ] (Open Source Programs Engineering) Retrain AskGPT bot on new data

**Comment by LiranCohen** [comment]
>(Web5 Team) Describe expected impact of this release. API Changes? (👍) DWN Wire Incompatibility requiring hosted DWN server reset? (👍). API changes seem to be backward compatible or non-user facing, the ADDITIONAL API we added is a `delete()` method on the `Record` class, so you can use that in place of `web5.dwn.records.delete(recordId)`

>(Web5 Team) Cut preview/alpha release for acceptance testing. Version [0.0.0-next-f71ce8a-20240718000106](https://www.npmjs.com/package/@web5/api/v/0.0.0-next-f71ce8a-20240718000106)

>(Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). Link to branch with passing bundler-bonanza w/ upgraded Web5 dep - https://github.com/TBD54566975/bundler-bonanza/pull/85
Bundle passes except for react native, it's able to pass locally but not sure what is going on with the bundler. @shamilovtim mentioned it might have to do with versioning but that Wallet works as expected.

**Comment by blackgirlbytes** [comment]
we already upgraded to this-- closing this issue
