### ISSUE TITLE
Add Section Images to Open Standards at TBD Blog Post

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1556]
# Add Section Images to Open Standards at TBD Blog Post

## 🚀 Goal
Read through our blog on[ Open Standards at TBD](https://developer.tbd.website/blog/open-standards-at-tbd), then create a descriptive / compelling visual for each section of the blog post.

## 🤔 Background
This issue focuses specifically on adding images to an existing blog post. Your contributions here will help readers understand our blog post's contents at a glance!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

## 🔑 Tasks and Acceptance Criteria
- [ ] Read through blog post for this task.
- [ ] Create image for each section in the blog (4 sections total).
- [ ] Submit PR with section images for review.

## 🌟 Resources
- [Open Standards at TBD](https://developer.tbd.website/blog/open-standards-at-tbd)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉
