### ISSUE TITLE
Fix Typos in Developer Website's Docs

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1561]
# Website Docs Typos

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

## 🔑 Tasks and Acceptance Criteria
1. API Reference Guides [page](https://developer.tbd.website/docs/api)
    - [ ] Fix "instutition" to be "institution"
    ![image](https://hackmd.io/_uploads/BydwIqyhA.png)
    - [ ] Fix "Self Sovereign Identity" to be "Self-Sovereign Identity" for consistency
    ![image](https://hackmd.io/_uploads/ryLeDcJ2C.png)
2. Web5 [page](https://developer.tbd.website/docs/web5/)
    - [ ] Change "regurgitate" to "recreate" for better translations across different languages
    ![image](https://hackmd.io/_uploads/S1Pdvq12A.png)
3. Resolve a DID [page](https://developer.tbd.website/docs/web5/decentralized-identifiers/how-to-resolve-a-did)
    - [ ] Example DID document needs comma, `"capabilityDelegation": ["#0"]` to `"capabilityDelegation": ["#0"],`
    ![image](https://hackmd.io/_uploads/BkLEA512R.png)
4. What Are VCs [page](https://developer.tbd.website/docs/web5/verifiable-credentials/what-are-vcs)
    - [ ] Fix "Affinidi Pet. Ltd" to be "Affinidi Pte. Ltd"
    ![image](https://hackmd.io/_uploads/BkVQlsy2C.png)
    - [ ] Fix "made up story" to be "made-up story"
    ![image](https://hackmd.io/_uploads/BkRSxi1nR.png)
    - [ ] Fix "employer(verifier)" to be "employer (verifier)" (space before parentheses)
    ![image](https://hackmd.io/_uploads/H1ydesJ3R.png)
    - [ ] Fix "pubic-private key pair" to be "public-private key pair"
    ![image](https://hackmd.io/_uploads/rJl9Wsk2A.png)
    - [ ] Fix "now verified payload" to be "now-verified payload"
    ![image](https://hackmd.io/_uploads/HyTa-o13R.png)
    - [ ] Capitalize "Looking to play around with verifiable credentials yourself?" to be "Looking to play around with Verifiable Credentials yourself?" for consistency
    ![image](https://hackmd.io/_uploads/HyFZGjynA.png)
5. Issue a VC [page](https://developer.tbd.website/docs/web5/verifiable-credentials/vc-issuance)
    - [ ] Capitalize Verifiable Credentials for consistency
    ![image](https://hackmd.io/_uploads/HkQwfok3R.png)
6. Verify Credentials [page](https://developer.tbd.website/docs/web5/verifiable-credentials/verify-vc)
    - [ ] Capitalize Verifiable Credentials (VC) for consistency
    ![image](https://hackmd.io/_uploads/B15ZXoJ3R.png)
    - [ ] Capitalize Verifiable Presentations (VP) for consistency
    ![image](https://hackmd.io/_uploads/HkWX7skhR.png)
    - [ ] Change "multiple things" to "multiple elements" for accuracy
    ![image](https://hackmd.io/_uploads/HJTL7oJhA.png)
7. VCs in DWNS [page](https://developer.tbd.website/docs/web5/verifiable-credentials/vcs-in-dwn)
    - [ ] Make "From" lowercase for "Querying VC from DWN"
    ![image](https://hackmd.io/_uploads/B149EskhC.png)
8. VC Workflow [page](https://developer.tbd.website/docs/web5/verifiable-credentials/fan-club-vc)
    - [ ] Fix "identitfiers" to be "identifiers"
    ![image](https://hackmd.io/_uploads/Sk4Zrsy30.png)
    - [ ] Fix "satifies" to be "satisfies"
    ![image](https://hackmd.io/_uploads/r1d7rs12R.png)
9. What are DWNs [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-dwns)
    - [ ] Add space between "Identifer(DID)" to be "Identifier (DID)"
    ![image](https://hackmd.io/_uploads/Sk0qBi12A.png)
    - [ ] Change "up the application layer" to be "up to the application layer" ("to" for clarity)
    ![image](https://hackmd.io/_uploads/B1weUiy2A.png)
10. Query DWN Records [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/query-from-dwn)
    - [ ] Fix "publshedAscending" to be "publishedAscending"
    ![image](https://hackmd.io/_uploads/r1T9UoJ3R.png)
11. Common Errors [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/troubleshooting/common-errors)
    - [ ] Fix "functon" to be "function"
    ![image](https://hackmd.io/_uploads/HJpsvjyhC.png)
12. Structuring a PFI App [page](https://developer.tbd.website/docs/tbdex/pfi/anatomy-of-a-pfi)
    - [ ] Fix "to to" to say "to" only once
    ![image](https://hackmd.io/_uploads/rkHrFjJ3A.png)
13. Creating Offerings [page](https://developer.tbd.website/docs/tbdex/pfi/creating-offerings)
    - [ ] Change "a example" to be "an example"
    ![image](https://hackmd.io/_uploads/S1_YFo1n0.png)
14. Sending RFQs [page](https://developer.tbd.website/docs/tbdex/wallet/send-rfq)
    - [ ] Fix "satifies" to "satisfies"
    ![image](https://hackmd.io/_uploads/SyEvqsy2A.png)
15. Issuer Overview [page](https://developer.tbd.website/docs/tbdex/issuer/overview)
    - [ ] Fix "hese" to be "these"
    ![image](https://hackmd.io/_uploads/S1R1ss12R.png)
16. Credential Issuance [page](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance)
    - [ ] Fix "implmented" to "implemented"
    ![image](https://hackmd.io/_uploads/rkl_ook3R.png)
17. Issuing a KCC [page](https://developer.tbd.website/docs/tbdex/issuer/kcc/kcc-issuer)
    - [ ] Fix "recieved" to be "received"
    ![image](https://hackmd.io/_uploads/r1llno1nR.png)
18. Make sure all tests are passing.

## 🌟 Resources
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of Hacktoberfest

.take

**Comment by imperialc0der** [comment]
.take
