### ISSUE TITLE
Create Your Own YouTube Video About Your Experience in TBD Hacktoberfest

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1685]
# Create Your Own YouTube Video About Your Experience in TBD Hacktoberfest

## 🚀 Goal
We want you to share your experience in Hacktoberfest with us in your own video content.

## 🤔 Background
This issue focuses specifically on documenting and summarizing your experience during this year's Hacktoberfest in your own YouTube video. Document your contributions, what you learned, and what you'd like to see next year. Your contribution will help others learn and get excited for future hackathons!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

## 🔑 Tasks and Acceptance Criteria
- [ ] You must host your content on your own channel.
- [ ] Submit your content to our External Contributions as a PR.

You must include the following in your PR:
- [ ] Thumbnail
- [ ] Title
- [ ] Link to content
- [ ] Your name

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉
