### ISSUE TITLE
Create Your Own TikTok Video About Key Management for DIDs

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1713]
# Create Your Own TikTok Video About Key Management for DIDs

## 🚀 Goal
We want you to share what you've learned about key management for decentralized identifiers (DIDs) in your own TikTok video.

## 🤔 Background
This issue focuses specifically on creating a TikTok video to teach others about DID key management. Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

## 🔑 Tasks and Acceptance Criteria
- [ ] You must host your content on your own TikTok channel.
- [ ] Submit your content in a new [Content Submission issue](https://github.com/TBD54566975/developer.tbd.website/issues/new/choose) to our External Contributions as a PR.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

You must include the following in your PR:
- [ ] Thumbnail
- [ ] Title
- [ ] Link to content
- [ ] Your name

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉
