### ISSUE TITLE
Create Your Own YouTube Video About Decentralized Web Nodes (DWNs)

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1740]
# Create Your Own YouTube Video About DWNs

## 🚀 Goal
Create your own YouTube video about decentralized web nodes (DWNs) on your YouTube channel.

## 🤔 Background
This issue focuses specifically on spreading more awareness about DWNs. Your contributions here will help you spread your knowledge across the web and to our community!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

## 🔑 Tasks and Acceptance Criteria
- [ ] You must host your content on your own YouTube channel.
- [ ] Submit your content in a new [Content Submission issue](https://github.com/TBD54566975/developer.tbd.website/issues/new/choose) to our External Contributions as a PR.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

You must include the following in your PR:
- [ ] Thumbnail
- [ ] Title
- [ ] Link to content
- [ ] Your name

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Chrissiku** [comment]
.take
