### ISSUE TITLE
[Web5 Upgrade]: `v0.12.0`

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/developer.tbd.website#1847]
### Tasks

- [x] (Web5 Team) Expected code cutoff date (Before TabConf 11/24 noon EST) Note - For announcements/conferences and other high-visibility releases, dev cutoff is 1 week prior to expected release to make way for downstream work - guides, docs, validating the release, etc.
- [x] (Web5 Team) Expected release date (ASAP Before 11/24 noon EST).
- [x] (Web5 Team) Describe expected impact of this release. API Changes? (👎) DWN Wire Incompatibility requiring hosted DWN server reset? (👍) Breaking change: Protocol Actions that include any of `read`, `query` or `subscribe` MUST contain all 3.
- [x] (Web5 Team) Cut preview/alpha release for acceptance testing. Version - [0.0.0-next-05e5b64-20241022171741](https://www.npmjs.com/package/@web5/api/v/0.0.0-next-05e5b64-20241022171741)
- [x] (Web5 Team) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza). [Link to branch](https://github.com/TBD54566975/bundler-bonanza/pull/88) with passing bundler-bonanza w/ upgraded Web5 dep -
- [x] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. Branch - [Link here](https://github.com/TBD54566975/developer.tbd.website/pull/1849)
- [X] (Open Source Programs Engineering) Open PR on this branch. PR - [Link here](https://github.com/TBD54566975/developer.tbd.website/pull/1849)
- [X] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. Deploy Preview - [Link here](https://deploy-preview-1849--tbd-website-developer.netlify.app)https://deploy-preview-1849--tbd-website-developer.netlify.app/
- [X] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo
- [X] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [x] (Open Source Programs Engineering) Manually check QuickStart (required as manual until Issue 1093 is completed)
- [x] (Open Source Programs Engineering) Check results of tests
- [x] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [x] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [x] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch
- [x] (Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream
