### ISSUE TITLE
Change how ToDo Tutorial Sets Up Local Storage

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#455]
Full description of how we may handle this more effectively is detailed by @kirahsapong here:

https://github.com/TBD54566975/developer.tbd.website/pull/447#discussion_r1189088662

Will require:

- [ ] Updating `incubating-web5-labs` ToDo app to take this approach, validating it works
- [ ] Releasing `incubating-web5-labs` with new version
- [ ] Updating the Dev Site ToDo tutorial to the new `incubating-web5-labs` version
- [ ] Updating the ToDo tutorial to describe the new approach in `incubating-web5-labs` and updating the code snippits to match.

**Comment by ALRubinger** [comment]
This is now out of date given new convenience API in `web.connect()`
