### ISSUE TITLE
[Web5 Upgrade]: 0.8.2

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#959]
### Tasks

- [x] (Web5 Team) Cut preview/alpha release for acceptance testing. Version: `0.8.2-alpha-20231101-b865b10`
- [x] (Open Source Programs Engineering) Run Web5 tests against [acceptance suite](https://github.com/TBD54566975/bundler-bonanza)
- [X] (Open Source Programs Engineering) Create new branch on site repo for the upgrade. 
  - Branch Name: [v0.8.2-release](https://github.com/TBD54566975/developer.tbd.website/tree/v0.8.2-release)
- [X] (Open Source Programs Engineering) Open PR on this branch. 
  - Link to PR: https://github.com/TBD54566975/developer.tbd.website/pull/960
- [X] (Open Source Programs Engineering) This will trigger a Deploy Preview on Netlify. 
  - Link to Deploy Preview on Netlify: ✅ 
  - https://deploy-preview-960--tbd-website-developer.netlify.app/
- [X] (Open Source Programs Engineering) Update the Web5 version to the alpha release in site monorepo on the upgrade branch
- [X] (Open Source Programs Engineering) Run the monorepo tests - this will cover code snippets and examples
- [X] (Open Source Programs Engineering) Check results of tests
  - Link to the tests results: ✅  [Passed](https://github.com/TBD54566975/developer.tbd.website/actions/runs/6788215375/job/18452703667)
- [X] (DevRel) If errors, issue updates to guides, examples in the release branch until tests pass
- [X] (Web5 Team) Cut release of Web5 available on [Releases Page](https://github.com/TBD54566975/web5-js/releases)
- [X] (Open Source Programs Engineering) Update Web5 version in site to new Web5 version on branch

Dimissed, since we are not publishing API Reference for Web5JS yet...
- [ ] ~~(Open Source Programs Engineering) The release of Web5 will trigger tbdocs automation and open a PR for that against the site. Merge that PR in the branch.~~
- [ ] ~~(Open Source Programs Engineering) Rebase and merge site to `main`, run tests, push upstream~~

**Comment by angiejones** [comment]
opened https://github.com/TBD54566975/web5-js/issues/260 for test failure

**Comment by angiejones** [comment]
opened https://github.com/TBD54566975/web5-js/issues/259 for test `readRecordByIdFromDid`

**Comment by angiejones** [comment]
`send()` failing. Not sure if it's because of the new record format. Asked here.

Failing tests:

- `sendRecordToRemoteDWNs`
- `sendProtocolToRemoteDWNs`
- `sendRecordToDWNOfRecipient`
